import React from "react";
import {
  Document,
  Page,
  Text,
  View,
  StyleSheet,
} from "@react-pdf/renderer";
import type { GeneratedPlan } from "@/types/plan";

const styles = StyleSheet.create({
  page: { padding: 40, fontSize: 10 },
  header: { marginBottom: 24 },
  title: { fontSize: 18, fontWeight: 700, marginBottom: 4 },
  subtitle: { fontSize: 9, color: "#666", marginBottom: 16 },
  coachBrand: { fontSize: 9, color: "#888", marginTop: 8 },
  section: { marginBottom: 20 },
  sectionTitle: { fontSize: 12, fontWeight: 700, marginBottom: 8 },
  dayCard: { marginBottom: 12, padding: 10, backgroundColor: "#f5f5f5", borderRadius: 4 },
  dayName: { fontSize: 11, fontWeight: 700, marginBottom: 4 },
  mealRow: { marginBottom: 4, flexDirection: "row", justifyContent: "space-between" },
  mealName: { flex: 1 },
  mealMacros: { color: "#666", fontSize: 9 },
});

interface PlanPDFProps {
  plan: GeneratedPlan;
  clientName: string;
  coachName: string;
  coachBrand?: string;
}

export function PlanPDFDocument({
  plan,
  clientName,
  coachName,
  coachBrand,
}: PlanPDFProps) {
  const weekly = plan.weekly_plan ?? [];
  const calorieTarget = plan.calorie_target ?? plan.user_stats?.calorie_target ?? 0;
  const proteinTarget = plan.protein_target ?? plan.user_stats?.protein_target_g ?? 0;

  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <View style={styles.header}>
          <Text style={styles.title}>
            {clientName}&apos;s Personalised Nutrition Plan
          </Text>
          <Text style={styles.subtitle}>
            Generated by NutriCoach AI · Tailored to your body & goals
          </Text>
          {(calorieTarget || proteinTarget) && (
            <Text style={styles.subtitle}>
              Targets: {calorieTarget} kcal/day · {proteinTarget}g protein/day
            </Text>
          )}
          <Text style={styles.coachBrand}>
            Your coach: {coachBrand || coachName}
          </Text>
        </View>

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>7-Day Meal Plan</Text>
          {weekly.map((day) => (
            <View key={day.day} style={styles.dayCard}>
              <Text style={styles.dayName}>
                {day.day} {day.type ? `· ${day.type}` : ""}
              </Text>
              {(day.meals ?? []).map((m, i) => (
                <View key={i} style={styles.mealRow}>
                  <Text style={styles.mealName}>{m.name}</Text>
                  <Text style={styles.mealMacros}>
                    {m.kcal} kcal · {m.protein_g}g protein
                  </Text>
                </View>
              ))}
            </View>
          ))}
        </View>
      </Page>
    </Document>
  );
}
