"use client";

import type { GeneratedPlan } from "@/types/plan";
import { PlanSummaryCards } from "./PlanSummaryCards";
import { PlanTabs } from "./PlanTabs";
import { Button } from "@/components/ui/Button";

interface PlanDisplayProps {
  plan: GeneratedPlan;
  weekStartDate?: string | null;
  name: string;
  goal: string;
  onGenerateNew: () => void;
}

export function PlanDisplay({
  plan,
  weekStartDate,
  name,
  goal,
  onGenerateNew,
}: PlanDisplayProps) {
  const displayName = plan.user_stats?.name ?? name;

  return (
    <div
      id="planOutput"
      className="bg-dark py-20 px-6"
    >
      <div className="max-w-[1100px] mx-auto">
        <div className="text-center mb-12">
          <h2 className="font-heading font-extrabold text-3xl md:text-4xl tracking-tight">
            {displayName}&apos;s Personalised {goal} Plan
          </h2>
          <p className="text-text-dim mt-2 text-sm">
            Generated by NutriCoach AI · Tailored to your body & goals
          </p>
        </div>

        <PlanSummaryCards plan={plan} />
        <PlanTabs plan={plan} weekStartDate={weekStartDate} />

        <div className="mt-12 flex justify-center">
          <Button variant="ghost" onClick={onGenerateNew}>
            Generate a New Plan
          </Button>
        </div>
      </div>
    </div>
  );
}
